import {
  LayoutDashboard, Building2, TrendingUp, Users, HardHat,
  Briefcase, UserCog, Headphones, Scale, Wallet,
  Megaphone, BarChart3, Shield, ShieldAlert, Database, Settings, Bell, FileText,
  Workflow, BrainCircuit, Plug, CalendarDays, LayoutGrid, Film, ShieldCheck, Upload, FileArchive, FileCheck,
  FolderOpen,
} from 'lucide-react';

export const dashboardNav = [
  { label: 'Home', href: '/dashboard', icon: LayoutDashboard },
  { label: 'Projects', href: '/admin/projects', icon: FolderOpen, permission: 'properties.view' },
  { label: 'Properties', href: '/dashboard/properties', icon: Building2, permission: 'properties.view' },
  { label: 'Buy2Flip', href: '/dashboard/buy2flip', icon: TrendingUp, permission: 'buy2flip.view' },
  { label: 'Leads', href: '/dashboard/leads', icon: Users, permission: 'leads.view' },
  { label: 'Construction', href: '/dashboard/construction', icon: HardHat, permission: 'construction.view' },
  { label: 'Management', href: '/dashboard/management', icon: Briefcase, permission: 'property_management.view' },
  { label: 'Customers', href: '/dashboard/customers', icon: UserCog, permission: 'customers.view' },
  { label: 'Support', href: '/dashboard/support', icon: Headphones, permission: 'support.view' },
  { label: 'Legal', href: '/dashboard/legal', icon: Scale, permission: 'legal.view' },
  { label: 'Finance', href: '/dashboard/finance', icon: Wallet, permission: 'finance.view' },
  { label: 'Marketing', href: '/dashboard/marketing', icon: Megaphone, permission: 'marketing.view' },
  { label: 'Reports', href: '/dashboard/reports', icon: BarChart3, permission: 'reports.view' },
  { label: 'Administration', href: '/admin/rbac', icon: Shield, permission: 'security.view' },
  { label: 'SOC Dashboard', href: '/admin/soc', icon: ShieldAlert, permission: 'security.view' },
  { label: 'DB Governance', href: '/admin/database', icon: Database, permission: 'security.view' },
  { label: 'Notifications', href: '/admin/notifications', icon: Bell, permission: 'security.view' },
  { label: 'Workflow Engine', href: '/admin/workflows', icon: Workflow, permission: 'security.view' },
  { label: 'AI Center', href: '/admin/ai', icon: BrainCircuit, permission: 'security.view' },
  { label: 'Financial Center', href: '/admin/finance', icon: Wallet, permission: 'security.view' },
  { label: 'CMS', href: '/admin/cms', icon: FileText, permission: 'security.view' },
  { label: 'Marketing Center', href: '/admin/marketing', icon: Megaphone, permission: 'security.view' },
  { label: 'API Gateway', href: '/admin/api-gateway', icon: Plug, permission: 'security.view' },
  { label: 'Scheduling', href: '/admin/scheduling', icon: CalendarDays, permission: 'security.view' },
  { label: 'Command Center', href: '/admin/command-center', icon: LayoutGrid, permission: 'security.view' },
  { label: 'DMS & Signing', href: '/admin/dms', icon: FileText, permission: 'security.view' },
  { label: 'Media Ops', href: '/admin/media-ops', icon: Film, permission: 'security.view' },
  { label: 'Media Review', href: '/admin/media-review', icon: FileArchive, permission: 'security.view' },
  { label: 'Doc Verification', href: '/admin/document-verification', icon: FileCheck, permission: 'security.view' },
  { label: 'Security Ops', href: '/admin/security-ops', icon: ShieldCheck, permission: 'security.view' },
  { label: 'Settings', href: '/dashboard/settings', icon: Settings },
];